import { Language } from './types';

export const COLORS = {
  background: '#050505', // Deep Space Black
  primary: '#8B5CF6', // Vivid Violet (Purple)
  secondary: '#06B6D4', // Cyan (now secondary)
  accent: '#F59E0B', // Amber/Gold
  success: '#00FF94', // Neon Green
  error: '#FF0055', // Neon Red
  glass: 'rgba(10, 10, 10, 0.6)',
  glassHover: 'rgba(20, 20, 20, 0.8)',
  glassBorder: 'rgba(255, 255, 255, 0.08)',
  textMain: '#FFFFFF',
  textMuted: '#94A3B8',
};

export const LANGUAGE_CODES: Record<Language, string> = {
  [Language.AUTO]: 'auto',
  [Language.AFRIKAANS]: 'af-ZA',
  [Language.ALBANIAN]: 'sq-AL',
  [Language.AMHARIC]: 'am-ET',
  [Language.ARABIC]: 'ar-SA',
  [Language.ARABIC_ALGERIA]: 'ar-DZ',
  [Language.ARABIC_BAHRAIN]: 'ar-BH',
  [Language.ARABIC_EGYPT]: 'ar-EG',
  [Language.ARABIC_IRAQ]: 'ar-IQ',
  [Language.ARABIC_ISRAEL]: 'ar-IL',
  [Language.ARABIC_JORDAN]: 'ar-JO',
  [Language.ARABIC_KUWAIT]: 'ar-KW',
  [Language.ARABIC_LEBANON]: 'ar-LB',
  [Language.ARABIC_MOROCCO]: 'ar-MA',
  [Language.ARABIC_OMAN]: 'ar-OM',
  [Language.ARABIC_PALESTINE]: 'ar-PS',
  [Language.ARABIC_QATAR]: 'ar-QA',
  [Language.ARABIC_SAUDI]: 'ar-SA',
  [Language.ARABIC_TUNISIA]: 'ar-TN',
  [Language.ARABIC_UAE]: 'ar-AE',
  [Language.ARABIC_YEMEN]: 'ar-YE',
  [Language.ARMENIAN]: 'hy-AM',
  [Language.ASSAMESE]: 'as-IN',
  [Language.AZERBAIJANI]: 'az-AZ',
  [Language.BASQUE]: 'eu-ES',
  [Language.BELARUSIAN]: 'be-BY',
  [Language.BENGALI]: 'bn-IN',
  [Language.BENGALI_BANGLADESH]: 'bn-BD',
  [Language.BENGALI_INDIA]: 'bn-IN',
  [Language.BOSNIAN]: 'bs-BA',
  [Language.BULGARIAN]: 'bg-BG',
  [Language.BURMESE]: 'my-MM',
  [Language.CATALAN]: 'ca-ES',
  [Language.CHINESE_MANDARIN_SIMPLIFIED]: 'zh-CN',
  [Language.CHINESE_MANDARIN_TRADITIONAL]: 'zh-TW',
  [Language.CHINESE_CANTONESE]: 'zh-HK', // Often used mapping for Cantonese in some systems, or yue-HK
  [Language.CROATIAN]: 'hr-HR',
  [Language.CZECH]: 'cs-CZ',
  [Language.DANISH]: 'da-DK',
  [Language.DUTCH]: 'nl-NL',
  [Language.DUTCH_BELGIUM]: 'nl-BE',
  [Language.ENGLISH_AUSTRALIA]: 'en-AU',
  [Language.ENGLISH_CANADA]: 'en-CA',
  [Language.ENGLISH_GHANA]: 'en-GH',
  [Language.ENGLISH_HK]: 'en-HK',
  [Language.ENGLISH_INDIA]: 'en-IN',
  [Language.ENGLISH_IRELAND]: 'en-IE',
  [Language.ENGLISH_KENYA]: 'en-KE',
  [Language.ENGLISH_NZ]: 'en-NZ',
  [Language.ENGLISH_NIGERIA]: 'en-NG',
  [Language.ENGLISH_PHILIPPINES]: 'en-PH',
  [Language.ENGLISH_SINGAPORE]: 'en-SG',
  [Language.ENGLISH_SOUTH_AFRICA]: 'en-ZA',
  [Language.ENGLISH_TANZANIA]: 'en-TZ',
  [Language.ENGLISH_UK]: 'en-GB',
  [Language.ENGLISH_US]: 'en-US',
  [Language.ESTONIAN]: 'et-EE',
  [Language.FILIPINO]: 'fil-PH',
  [Language.FINNISH]: 'fi-FI',
  [Language.FRENCH]: 'fr-FR',
  [Language.FRENCH_BELGIUM]: 'fr-BE',
  [Language.FRENCH_CANADA]: 'fr-CA',
  [Language.FRENCH_SWITZERLAND]: 'fr-CH',
  [Language.GALICIAN]: 'gl-ES',
  [Language.GEORGIAN]: 'ka-GE',
  [Language.GERMAN]: 'de-DE',
  [Language.GERMAN_AUSTRIA]: 'de-AT',
  [Language.GERMAN_SWITZERLAND]: 'de-CH',
  [Language.GREEK]: 'el-GR',
  [Language.GUJARATI]: 'gu-IN',
  [Language.HAUSA]: 'ha-NG',
  [Language.HEBREW]: 'he-IL',
  [Language.HINDI]: 'hi-IN',
  [Language.HUNGARIAN]: 'hu-HU',
  [Language.ICELANDIC]: 'is-IS',
  [Language.IGBO]: 'ig-NG',
  [Language.INDONESIAN]: 'id-ID',
  [Language.IRISH]: 'ga-IE',
  [Language.ITALIAN]: 'it-IT',
  [Language.ITALIAN_SWITZERLAND]: 'it-CH',
  [Language.JAPANESE]: 'ja-JP',
  [Language.JAVANESE]: 'jv-ID',
  [Language.KANNADA]: 'kn-IN',
  [Language.KAZAKH]: 'kk-KZ',
  [Language.KHMER]: 'km-KH',
  [Language.KOREAN]: 'ko-KR',
  [Language.LAO]: 'lo-LA',
  [Language.LATVIAN]: 'lv-LV',
  [Language.LITHUANIAN]: 'lt-LT',
  [Language.MACEDONIAN]: 'mk-MK',
  [Language.MALAY]: 'ms-MY',
  [Language.MALAYALAM]: 'ml-IN',
  [Language.MARATHI]: 'mr-IN',
  [Language.MONGOLIAN]: 'mn-MN',
  [Language.NEPALI]: 'ne-NP',
  [Language.NORWEGIAN]: 'no-NO',
  [Language.PERSIAN]: 'fa-IR',
  [Language.POLISH]: 'pl-PL',
  [Language.PORTUGUESE]: 'pt-PT',
  [Language.PORTUGUESE_BRAZIL]: 'pt-BR',
  [Language.PUNJABI]: 'pa-IN',
  [Language.ROMANIAN]: 'ro-RO',
  [Language.RUSSIAN]: 'ru-RU',
  [Language.SERBIAN]: 'sr-RS',
  [Language.SINHALA]: 'si-LK',
  [Language.SLOVAK]: 'sk-SK',
  [Language.SLOVENIAN]: 'sl-SI',
  [Language.SOMALI]: 'so-SO',
  [Language.SPANISH_SPAIN]: 'es-ES',
  [Language.SPANISH_ARGENTINA]: 'es-AR',
  [Language.SPANISH_BOLIVIA]: 'es-BO',
  [Language.SPANISH_CHILE]: 'es-CL',
  [Language.SPANISH_COLOMBIA]: 'es-CO',
  [Language.SPANISH_COSTA_RICA]: 'es-CR',
  [Language.SPANISH_DOMINICAN]: 'es-DO',
  [Language.SPANISH_ECUADOR]: 'es-EC',
  [Language.SPANISH_EL_SALVADOR]: 'es-SV',
  [Language.SPANISH_GUATEMALA]: 'es-GT',
  [Language.SPANISH_HONDURAS]: 'es-HN',
  [Language.SPANISH_MEXICO]: 'es-MX',
  [Language.SPANISH_NICARAGUA]: 'es-NI',
  [Language.SPANISH_PANAMA]: 'es-PA',
  [Language.SPANISH_PARAGUAY]: 'es-PY',
  [Language.SPANISH_PERU]: 'es-PE',
  [Language.SPANISH_PUERTO_RICO]: 'es-PR',
  [Language.SPANISH_US]: 'es-US',
  [Language.SPANISH_URUGUAY]: 'es-UY',
  [Language.SPANISH_VENEZUELA]: 'es-VE',
  [Language.SWAHILI]: 'sw-KE',
  [Language.SWEDISH]: 'sv-SE',
  [Language.TAMIL]: 'ta-IN',
  [Language.TELUGU]: 'te-IN',
  [Language.THAI]: 'th-TH',
  [Language.TURKISH]: 'tr-TR',
  [Language.UKRAINIAN]: 'uk-UA',
  [Language.URDU]: 'ur-PK',
  [Language.UZBEK]: 'uz-UZ',
  [Language.VIETNAMESE]: 'vi-VN',
  [Language.WELSH]: 'cy-GB',
  [Language.YORUBA]: 'yo-NG',
  [Language.ZULU]: 'zu-ZA'
};

export const DEFAULT_LANGUAGE_CONFIG = {
  source: Language.AUTO,
  target: Language.SPANISH_SPAIN,
};